package com.openclassrooms.realestatemanager.model.sqlite

import android.content.Context
import android.content.ContentValues
import androidx.room.*
import androidx.sqlite.db.SupportSQLiteDatabase
import com.openclassrooms.realestatemanager.model.coremodel.*
import com.openclassrooms.realestatemanager.model.sqlite.dao.*
import com.openclassrooms.realestatemanager.model.sqlite.dataconverters.DateConverter
import com.openclassrooms.realestatemanager.model.sqlite.dataconverters.StringsListConverter

/**************************************************************************************************
 * SQLite Database management
 *************************************************************************************************/

@Database(entities= [Property::class, Realtor::class, PropertyType::class, Extra::class, ExtrasPerProperty::class, Picture::class],
        version=1,
        exportSchema = false)

@TypeConverters(DateConverter::class, StringsListConverter::class)

abstract class SQLiteDatabase:RoomDatabase() {

    /**DAO items**/

    abstract val propertyDAO: PropertyDAO
    abstract val realtorDAO: RealtorDAO
    abstract val propertyTypeDAO: PropertyTypeDAO
    abstract val extraDAO: ExtraDAO
    abstract val extrasPerPropertyDAO:ExtrasPerPropertyDAO
    abstract val pictureDAO:PictureDAO

    companion object {

        /**Database instance**/

        @Volatile private var INSTANCE: SQLiteDatabase? = null

        /**Data used to prepopulate the database**/

        private const val CLASS_NAME_REALTOR="Realtor"
        private const val CLASS_NAME_PROPERTY_TYPE="PropertyType"
        private const val CLASS_NAME_EXTRA="Extra"
        private const val FIELD_NAME_NAME="name"
        private val DATA_REALTOR=listOf("Unknown")
        private val DATA_PROPERTY_TYPE=listOf(
                "House", "Condo", "Town home", "Multi-family", "Land", "Manufactured", "Other")
        private val DATA_EXTRA=listOf(
                "Nearby transports", "Nearby school", "Nearby supermarket", "Nearby hospital",
                "Elevator", "Air conditioning", "Garage", "Swimming pool")

        /**Creates an instance of the database**/

        fun getInstance(context: Context): SQLiteDatabase {
            if (INSTANCE == null) {
                synchronized(SQLiteDatabase::class.java) {
                    if (INSTANCE == null) {
                        INSTANCE = Room.databaseBuilder(context.applicationContext,
                                SQLiteDatabase::class.java, "RealEstateManager.db")
                                .addCallback(prepopulateDatabase())
                                .build()
                    }
                }
            }
            return INSTANCE!!
        }

        /**Populates the database with initialization data**/

        private fun prepopulateDatabase(): Callback {
            return object : RoomDatabase.Callback() {
                override fun onCreate(db: SupportSQLiteDatabase) {
                    super.onCreate(db)
                    prepopulateData(db, CLASS_NAME_REALTOR, FIELD_NAME_NAME, DATA_REALTOR)
                    prepopulateData(db, CLASS_NAME_PROPERTY_TYPE, FIELD_NAME_NAME, DATA_PROPERTY_TYPE)
                    prepopulateData(db, CLASS_NAME_EXTRA, FIELD_NAME_NAME, DATA_EXTRA)
                }
            }
        }

        /**Populates an entity with a value (id is autogenerated)**/

        private fun prepopulateData(db:SupportSQLiteDatabase, className:String, fieldName:String, values:List<String>){
            val contentValues = ContentValues()
            for(value in values){
                contentValues.put(fieldName, value)
                db.insert(className, OnConflictStrategy.IGNORE, contentValues)
            }
        }
    }
}